# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa0a9283ae0fb974f5cc87f5dc33bc9d2e131df5c53c687af76abe72b92b004f47d91d22283d351f6d93519f500e7bea69730bdf657a253939bf2de7e65f239

test:
  secret_key_base: cfc645e1b6cc491d9439fa2b6e2121c88d66690a0e06062b7f0e87cb9cf20b7629766d6041f6c05ad6d55926b1a8b71284c36d3839ab63d749de16ec0349ed13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
